version: "3.8"

services:
  postgres_strapi_blog:
    image: postgres
    container_name: postgres_strapi_blog
    hostname: postgres_strapi_blog
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi_password
      POSTGRES_DB: strapi_db
    volumes:
      - postgres_strapi_blog:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  postgres_strapi_blog: